name: Build Debian Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
          echo ::set-env name=FEEDBACKMAIL::aappaass@hash.fyi
      - name: Compile script
        run: |
          add-apt-repository ppa:neurobin/ppa
          apt update
          apt install shc
          shc -f aappaass.sh -r -m ${{ env.FEDDBACKMAIL }}
          cp aappaass.sh.x pkgroot/usr/bin/aappaass
      - uses: jiro4989/build-deb-action@v3
        name: Build deb package
        with:
          package: aappaass
          package_root: pkgroot
          maintainer: Renato Zippert
          version: v${{ env.RELEASE_VERSION }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'pulseaudio-utils'
          desc: 'Manages "passthrough" sinks for PulseAudio.'
      - uses: actions/upload-artifact@v3
        name: Upload deb package
        with:
          name: aappaass_${{ env.RELEASE_VERSION }}_amd64.deb
          if-no-files-found: error
          path: |
            ./aappaass_${{ env.RELEASE_VERSION }}_amd64.deb
