name: Build Debian Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
      - uses: jiro4989/build-deb-action@v3
        with:
          package: aappaass
          package_root: pkgroot
          maintainer: Renato Zippert
          version: ${GITHUB_REF##*/} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'pulseaudio-utils'
          desc: 'Manages "passthrough" sinks for PulseAudio.'
      - uses: actions/upload-artifact@v3
        with:
          name: aappaass_${GITHUB_REF##*/v}_amd64.deb
          if-no-files-found: error
          path: |
            ./aappaass_${GITHUB_REF##*/v}_amd64.deb
